### ISSUE TITLE
Is this project still current?

### ISSUE THREAD

**Issue by mikebronner** [bmuller/campfirer#2]
Hi,
I just wanted to verify if this project was still functional, or if it has been abandoned? I tried to use the campfirer.com gateway to test it, but was unable to connect.

**Comment by bmuller** [comment]
Hey @mikebronner - sorry, didn't see this until now.  So - the short answer is no, it's not still current (I haven't used campfire in a really long time) - BUT if the API hasn't changed much then it should theoretically still work (if you use option 2 described in the README intro).

**Comment by mikebronner** [comment]
No worries, I closed it because I haven't been using it anymore. :)
